### ISSUE TITLE
多实例

### ISSUE THREAD

**Issue by jixiaohan** [giscafer/angular-webuploader#1]
请问在同一控制器内多次使用本指令怎么进行实例化

**Comment by giscafer** [comment]
现在指令可以一个页面内重复使用呀，不影响。
**是不是图片效果？**
![qq 20160721214132](https://cloud.githubusercontent.com/assets/8676711/17024846/fb511ca6-4f8b-11e6-8d6e-150fcf4d6882.jpg)
![qq 20160721214114](https://cloud.githubusercontent.com/assets/8676711/17024845/fb4f1cee-4f8b-11e6-9b15-b60eb6fd6163.jpg)
