### ISSUE TITLE
请问一下有没有遇到route切换之后，webuploader无法创建的问题

### ISSUE THREAD

**Issue by MJPiero** [giscafer/angular-webuploader#2]
就是只有初始化的时候可以正常创建，但是切换route之后，就无法创建了，而且再切换回之前创建成功的route也是失败的

**Comment by giscafer** [comment]
给个demo链接看看

**Comment by MJPiero** [comment]
谢谢，我找到问题了，是ngrepeat 没有加载完成我就调用了创建方法。
